### ISSUE TITLE
[IPTV connector] Kodi exits on installing addon from the repo

### ISSUE THREAD

**Issue by oedsie** [dut-iptv/dut-iptv#77] opened 2021-11-17 22:12 UTC
The simple iptv connector keeps shutting my kodi down. Also using a Nvidia Shield 2019 kodi 19.3

_Originally posted by @oedsie in https://github.com/dut-iptv/dut-iptv/issues/43#issuecomment-971836823_

**Comment by dut-iptv** [comment] 2021-11-25 18:31
I think I have come across this issue once while installing the IPTV connector addon on a friends Shield. Was not able to ascertain what the issue was but was able to workaround it by installing the addon by hand.

You can do this by downloading the addon zip from  the repository and unpacking the zip file in your Kodi addon folder. After restarting Kodi you can activate the addon from the my add-ons menu

**Comment by dut-iptv** [comment] 2021-11-26 14:38
Version 1.2.7 of the various video addons includes the option to install the connector from the settings menu in the video addon. Please follow the prompts to install and enable the connector

**Comment by oedsie** [comment] 2021-12-01 10:08
Even with the workaround and the provided update in 1.2.7. whilst enabeling the connector addon Kodi keeps shutting down.

**Comment by dut-iptv** [comment] 2021-12-01 11:40
I was able to reproduce your issue on an updated Shield with the latest Kodi. The issue does not seem to occur on Windows.

The issue appears to occur when trying to open the information screen for the addon.

I was able to enable and use the addon by doing the following:
-Install the addon using the workaround
-Enable the addon by Right clicking/using the context menu. 

Will investigate further to hopefully fix the underlying problem

**Comment by dut-iptv** [comment] 2021-12-01 12:32
It seems the problem is related to including PVR IPTV Simple Client as a dependancy in the addons.xml file.
This also explains why non of my other addons exhibit the same behaviour.
Changing the required version (a couple addons changed their versioning to follow Kodi's versioning) does seem to solve the problem, but not if Kodi already has some of the information cached.

The next update to the connector will include changes to the addon.xml that hopefully will fix these issues for new installations. For existing installations the workaround will probably be required for now.

**Comment by oedsie** [comment] 2021-12-01 13:11
> It seems the problem is related to including PVR IPTV Simple Client as a dependancy in the addons.xml file. This also explains why non of my other addons exhibit the same behaviour. Changing the required version (a couple addons changed their versioning to follow Kodi's versioning) does seem to solve the problem, but not if Kodi already has some of the information cached.
> 
> The next update to the connector will include changes to the addon.xml that hopefully will fix these issues for new installations. For existing installations the workaround will probably be required for now.

**Comment by oedsie** [comment] 2021-12-01 13:13
Somehow I guess it has something to do with file management on the Shield. Those devices aren't rooted. So referencing the local file storage is not possible. Does the connector need to have root acces?

**Comment by dut-iptv** [comment] 2021-12-07 15:45
With 1.3.0 I am able to install the connector the standard way (from the repository) and using the workaround from any of the video addons on an Android phone (without root). Will also test my Nvidia Shield TV as soon as I can.

**Comment by dut-iptv** [comment] 2021-12-08 06:16
Version 1.3.0 also works/installs without issues on my Shield TV using both the default way and using the workaround. Marking this as fixed.

**Closed by dut-iptv** 2021-12-08 06:16 UTC
Labels: bug
