### ISSUE TITLE
[Ziggo][1.0.8] Playback error

### ISSUE THREAD

**Issue by dvdevil** [dut-iptv/dut-iptv#21] opened 2021-02-24 20:44 UTC
[kodi log.zip](https://github.com/dut-iptv/dut-iptv/files/6042054/kodi.log.zip)
![Naamloos](https://user-images.githubusercontent.com/79605796/109067844-5a595f80-76ef-11eb-90af-6841de26f1e7.jpg)
Kodi Matrix x64 ziggo channels not working, error cannot play file.
Windows 10 x64 .
Tested on 5 windows 10 pc,s i give up,back to leia...

**Comment by Pukson** [comment] 2021-03-01 13:29
Got the exact same error but then with Tmobile. I believe it has something to do with input stream. As I can't find it anymore within the addons and the button install widevine doesn't work anymore

**Comment by dut-iptv** [comment] 2021-03-02 12:05
@dvdevil Is this issue still present?

I'am not able to reproduce the issue on Windows or Android in the Ziggo addon.

The attached log does point to a problem in retrieving a Widevine license, but if this is a structural problem I would expect it to be reproducably by anyone.
Could be a temporary server issue at Ziggo.

Have you tried resetting the addon after the Matrix upgrade and logging in again?
Does the problem exist on all channels or only on commercial channels?

@Pukson Your problem seems unrelated to this issue. Please create a separate issue if your problem persists (consider reinstalling matrix and the addon first or resetting the addon)

**Comment by dvdevil** [comment] 2021-03-02 13:38
Just tried again but the same error resetting wont help,all channels.
The strange thing is that videoland works...

**Comment by dvdevil** [comment] 2021-03-02 23:08
They are two different files of the add-on for Matrix and Leia. There is just a bug in the Matrix version. Something went wrong converting string composition into
code: 

1
\plugin.video.ziggo\resources\lib\base\l7\plugin.py


and

code:
1
\plugin.video.ziggo\resources\lib\base\l6\inputstream.py

**Comment by dvdevil** [comment] 2021-03-03 12:51
After installing a fresh windows 10 install getting this error while logging in to ziggo.
![Naamloos](https://user-images.githubusercontent.com/79605796/109808509-7f862a80-7c27-11eb-993b-037f876b4a56.jpg)

**Comment by dut-iptv** [comment] 2021-03-05 21:42
See #25, please try again with 1.1.0.

It is possible that a recent change by Ziggo to the login and playback API is to blame.
The login problem should be fixed in 1.1.0., the playback problem might be fixed with 1.1.0.
A rewrite of the Ziggo addon to better suit the Ziggo API changes will follow in the next 1 or 2 weeks.

**Comment by dvdevil** [comment] 2021-03-05 22:19
Login works now but i am back to mi first pos cannot play file....

**Comment by tlandman** [comment] 2021-03-07 13:45
> Login works now but i am back to mi first post cannot play file....

I have the same issue. Login works, but can't play and no EPG data.

**Comment by dvdevil** [comment] 2021-03-12 20:27
Any beta to test?

**Comment by doormalena** [comment] 2021-03-14 09:43
I am having the same issue on Windows 10 + Matrix. 
Previously I had the `SharedProfileID' issue (after upgrading from Kodi 18.9 to 19) mentioned earlier in this thread, however that is fixed by resetting my settings back to default.

**Comment by dvdevil** [comment] 2021-03-14 11:43
> I am having the same issue on Windows 10 + Matrix.
> Previously I had the `SharedProfileID' issue (after upgrading from Kodi 18.9 to 19) mentioned earlier in this thread, however that is fixed by resetting my settings back to default.

Ok working for you do you have a screenshot with al live channel?

**Comment by doormalena** [comment] 2021-03-14 11:46
Does this help @dvdevil?
![image](https://user-images.githubusercontent.com/8328876/111067173-43728580-84c3-11eb-9698-f15c5a075adb.jpg)

**Comment by dvdevil** [comment] 2021-03-14 11:48
pff yes same over here........

**Comment by dut-iptv** [comment] 2021-03-14 14:19
Loggin issues regarding the SharedProfileID are seperate of this playback issue and should not be discussed here (and those are fixed).

Earlier logs seem to indicate a problem with retrieving a Widevine license that only influence some Ziggo accounts. 

Ziggo has been a major pain because of the amount of difference between API communication that seems to depend on among others your subscription (Next box or not) and possibly if you are former UPC or not. This makes debugging very difficult because what works for some, might not work for others.

I am uploading version 1.1.2 that changes a small part of the license request part of the addon which might fix things but most likely will not for most.

To further debug the problems there are 2 options:
1. Someone provides me on with their login on dut-iptv at tutanota.com (easier, but not preferred)
2. Someone provides me with the following data:

-Start an **incognito** tab in Chrome on Windows
-Press F12
-Open the network tab in the developers console
-Open https://www.ziggogo.tv/nl/tv/channel-asset.html/lgi-nl-prod-master%3ANL_000004_019461/location/65535.html
-Login with your credentials
-Start the RTL 4 live stream
-Find the second mention of eme and right click it and select "Copy" -> "Copy as Powershell"
-Post the results (remove possible sensitive information such as your username en OESP-Tokens)

**Comment by tlandman** [comment] 2021-03-14 19:40
It fixed it for me for now, thank you!

**Comment by dvdevil** [comment] 2021-03-14 20:49
You are lucky

**Comment by llentjes** [comment] 2021-03-15 06:53
Hi,

Is this what you are looking for? (I am not sure, since this is the first "eme" (and longer):

Invoke-WebRequest -Uri "https://obo-prod.oesp.ziggogo.tv/oesp/v4/NL/nld/web/license/eme" `
-Method "POST" `
-Headers @{
"sec-ch-ua"="`"Google Chrome`";v=`"89`", `"Chromium`";v=`"89`", `";Not A Brand`";v=`"99`""
  "sec-ch-ua-mobile"="?0"
  "X-OESP-Username"="Username"
  "X-OESP-License-Token"="Token"
  "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
  "X-OESP-DRM-SchemeIdUri"="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
  "X-OESP-Token"="Token"
  "X-OESP-License-Token-Type"="velocix"
  "X-OESP-Content-Locator"="urn:orion:media:std:lgi-nl-prod-master:NL_000004_019461_Orion-DASH"
  "Accept"="*/*"
  "Origin"="https://www.ziggogo.tv"
  "Sec-Fetch-Site"="same-site"
  "Sec-Fetch-Mode"="cors"
  "Sec-Fetch-Dest"="empty"
  "Referer"="https://www.ziggogo.tv/"
  "Accept-Encoding"="gzip, deflate, br"
  "Accept-Language"="nl-NL,nl;q=0.9"
}

**Comment by dut-iptv** [comment] 2021-03-15 07:14
@llentjes That is exactly what I am looking for and it is what I am expecting to see. But if I understand correctly you don't have a problem with Live channels in the addon (which some do have problems with). So i'm not sure if this info from your account will help the others in this thread or help me fix your problem with replay TV.

From you I would like this same output but from a stream that does not play in the addon and does play on the Ziggo Go website. This would help pinpoint if your problem is also related to the license retrieval or to some other error

**Comment by llentjes** [comment] 2021-03-15 07:20
@dut-iptv : indeed live tv works with me.
See #29, this problem exists with me. I understand this is a different problem. I will post the requested information in the other thread.

**Comment by dvdevil** [comment] 2021-03-15 09:43
Ok i have register account on tutanota.com but wats the email to send the ziggo pass..

**Comment by dut-iptv** [comment] 2021-03-15 17:31
@dvdevil Check the mailadress you used to message me

**Comment by dvdevil** [comment] 2021-03-15 18:25
there is no other way to send mail because they no longer give me access

**Comment by dut-iptv** [comment] 2021-03-15 18:40
You can just send email from any mailadress to dut-iptv@tutanota.com. Make sure the information you provided is valid.

**Comment by dvdevil** [comment] 2021-03-15 19:35
ok mail is send

**Comment by dut-iptv** [comment] 2021-03-15 20:09
@dvdevil Information received. 

I had no problems playing Live TV or Replay TV with the latest version (1.1.2) using Kodi 19.0 on Windows x64 with the information you provided.

Could you check if the addon works for you with the current information you provided?
Don't forget to change your password asap.

Looking at the information you supplied and what seemed to work (for me right now) and not work (for you before) I'm wondering if special characters (such as !) are to blame for the problems. 

Do other people who experience problems at this time have special characters (other than A-Z, a-z and 0-9) in their passwords?
If so try to change your pass to exclude special characters to see if this is to blame.

**Comment by dvdevil** [comment] 2021-03-15 20:50
i give up i can't get it to work...thanks

**Comment by dvdevil** [comment] 2021-03-15 23:46
My brother tested kodi matrix with the addon and it doesn't work for him either, and he lives in another city.

**Comment by dvdevil** [comment] 2021-03-16 14:00
> I am having the same issue on Windows 10 + Matrix.
> Previously I had the `SharedProfileID' issue (after upgrading from Kodi 18.9 to 19) mentioned earlier in this thread, however that is fixed by resetting my settings back to default.

is your problem now solved?

**Comment by dvdevil** [comment] 2021-03-16 15:14
2021-03-16 15:05:46.925 T:6736    ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2021-03-16 15:05:46.925 T:6736    ERROR <general>: CCurlFile::Open failed with code 400 for https://obo-prod.oesp.ziggogo.tv/oesp/v4/NL/nld/web/license/eme:
                                                   
2021-03-16 15:05:46.925 T:6736    ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2021-03-16 15:05:46.925 T:6736    ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
2021-03-16 15:05:46.925 T:6736    DEBUG <general>: AddOnLog: inputstream.adaptive: CDMMessage: 4 arrived!
2021-03-16 15:05:46.925 T:6736    ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
2021-03-16 15:05:46.925 T:6736    DEBUG <general>: AddOnLog: inputstream.adaptive: Session::~Session()
2021-03-16 15:05:46.928 T:6736    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:11189/ziggo/dash/NL_000008_019442;vxttoken=WIDEVINETOKEN/manifest.mpd|User-Agent=Mozilla/5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome/87.0.4280.88%20Safari/537.36&X-OESP-License-Token-Type=velocix&X-OESP-Token=eyJ0eXAiOiJKV1QiLCJraWQiOiJvZXNwX3Rva2VuX3Byb2RfMjAyMDA4MTkiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjUxNzc2OF9ubCIsImlzcyI6IndlYi1hcGktcHJvZC1vYm8uaG9yaXpvbi50diIsImV4cCI6MTYxNTkxNDE2NywiaWF0IjoxNjE1OTA2OTY3LCJzaWQiOiJkYWUyZTdjY2Q2NzNiODQ5NGNkMTFjM2RjMGU4NWYxMGQ5YjExNjdmMTI3NzBiNWVlNDkzMDcxNmVhNjdhOWIxIn0.0uzW6f9GiLRERElLncm-tgoLeX7FLi3b330A_yOlfmY&X-OESP-Username=dvdevil&X-OESP-License-Token=cGF0aFVSST0lMkZkYXNoJTJGTkxfMDAwMDA4XzAxOTQ0MiUyRiUyQSZleHBpcnk9MTYxNTkwNzc0NiZmbj1zaGEyNTYmcmV1c2U9LTEmYy1pcC11bmxvY2tlZD0xJnglM0FndWlkPWZhYjIyYTdjLWYzMzAtNDVlNy1hNTkzLWFjMzg4ODExNTdjMCZ4JTNBc3RyZWFtc2Vzc2lvbmlkPWM1ODQ4YzgxLThmNTMtNDY0YS05MzlhLTEzYjgyZjliOGE0MCZjLWlkPTEyNTE3NzY4LDcyOTJiMmY2NjdmMjZkOGYyMWY5MGM5ODUyMWI2MjJmNjc0ZjVkMTU5ZTZiYzBhMmEyYmM3ZTEyYjQwNGM5MTY%3D&X-OESP-DRM-SchemeIdUri=urn%3Auuid%3Aedef8ba9-79d6-4ace-a3c8-27dcd51d21ed&X-OESP-Content-Locator=urn%3Aorion%3Amedia%3Astd%3Algi-nl-prod-master%3ANL_000008_019442_Orion-DASH]
2021-03-16 15:05:46.928 T:6736     INFO <general>: CVideoPlayer::OnExit()

**Comment by dvdevil** [comment] 2021-03-20 15:07
Would it be that the addon only searches for HD channels, because I only have FTA channels from Ziggo?

**Comment by roykaandorp** [comment] 2021-03-28 17:58
Here it's also not working with the newest addon. When logging in with chrome at "https://www.ziggogo.tv/nl/tv/channel-asset.html/lgi-nl-prod-master%3ANL_000004_019461/location/65535.html" the log looks exactly the same as llentjes his log. 
I found out that when I use a vpn it does work! However the vpn I use is not fast enough to watch in HD. Is there anything I could try more?

**Comment by dvdevil** [comment] 2021-03-28 19:52
I tried with the IP address of the neighbors but it didn't work with that ... Playback Error

**Comment by roykaandorp** [comment] 2021-03-28 20:54
You have to edit the hosts file, in Windows it's "C:\Windows\System32\drivers\etc\hosts"
The add "95.101.21.123 obo-prod.oesp.ziggogo.tv" to it, after that open "cmd" and enter "ipconfig /flushdns".
In linux it's "/etc/hosts" but if you're using LibreELEC/CoreELEC, it's probably a "read only" file system.
Maybe configuring another dns server will work either. Would be best to edit the code, so it will use an alternative dns server to resolve the domainname I think, I will look at it shortly

**Comment by dvdevil** [comment] 2021-03-28 21:12
You are my Hero it works now thanks..................

**Comment by roykaandorp** [comment] 2021-03-29 14:05
@dvdevil You're welcome, don't forget to remove that line from the hosts file when there is a (better) solution.
Tried without the line in hosts with an alternative dns "1.1.1.1 and 1.0.0.1". This seems also to work, perhaps a better solution. With that dns it redirects that host name to "88.221.24.59" at the moment

**Comment by dvdevil** [comment] 2021-03-29 14:47
At the moment it works great so as long as there is no update from the Addon I keep using it.
Thanks again

**Comment by dut-iptv** [comment] 2021-03-30 20:26
@roykaandorp Pretty good find. Also explains why I face no problems in testing as I never used a Ziggo DNS server. Strange that Ziggo DNS servers return different IPs and break the addons functionality. I dont really consider this an addon bug, but will add some explanations to the readme to offer workarounds like changing dns server. Might also consider trying to create a workaround in the addon itself.

**Comment by roykaandorp** [comment] 2021-03-31 18:28
Actually I didn't use a ziggo dns either. Found here an explanation how it's possible that people can get different ip addresses from different locations. https://serverfault.com/questions/835660/cdn-how-is-it-possible-that-my-dns-delivers-a-different-ip-depending-on-the-vis
An option in the addon to resolve with an alternative dns would be great

**Comment by dvdevil** [comment] 2021-04-04 08:58
Thanks dut-iptv  fixed in the latest addon 1.1.3.

**Comment by dut-iptv** [comment] 2021-04-04 09:29
@dvdevil Good to hear, thanks for the debugging. 1.1.3 does in fact include a specific fix for this issue (use 1.0.0.1 for retrieving the IP of obo-prod.oesp.ziggogo.tv and use this instead of the IP that is returned by your usual DNS)

Thanks to @roykaandorp for supplying to information that helped resolve this issue.

Closing this for now

**Closed by dut-iptv** 2021-04-04 09:29 UTC
Labels: bug
