### ISSUE TITLE
[Ziggo Go][1.0.0] The dependency on inputstream.adaptive 2.4.4 could not be satisfied

### ISSUE THREAD

**Issue by tlouisse** [dut-iptv/dut-iptv#35] opened 2021-04-07 18:35 UTC
**Describe the bug**
When trying to install the Ziggo Go add-on, I get the message `The dependency on inputstream.adaptive 2.4.4 could not be satisfied` in the top right corner.

**To Reproduce**
1. Go to 'Add-ons' -> 'Install from Repository' 
2. Go to 'Dutch IPTV repository'  -> 'Video add-ons' -> 'Ziggo Go'
3. Press 'Install'
4. Select "Verison 1.0.0" of Dutch IPTV Repository
5. A screen with 10 dependencies pops up (amongst wich inputstream.adaptive 2.4.4). N.B.: all deps are `(installed)`
6. Press OK
7. Error message `The dependency on inputstream.adaptive 2.4.4 could not be satisfied` appears in the top right corner and installation halts

**Expected behavior**
The add-on should install without errors.

**Device**
- Type: [Raspberry Pi]
 - OS: [Raspbian]
 - Version [Kodi 18.7]

**Comment by dut-iptv** [comment] 2021-04-08 18:03
This is not a bug in my addons or repo.

This is a shortcoming of your chosen OS, which does not readily make available up to date standard Kodi components and also does not provide an up to date Kodi (19) binary.

Ziggo on Leia has not been supported for a while anyway and recent changes to the Ziggo API have rendered the addon unusable on Leia.

My advice is to do one of the following:

-Switch OS to Libreelec beta with Kodi 19
-Stay on Raspbian and build Kodi 19 and inputstream adaptive from source
-Stay on Raspbian and wait for the maintainers to release a Kodi 19 binary and recent inputstream adaptive

Closing as it is not a bug/problem in any of the components in this repo

**Closed by dut-iptv** 2021-04-08 18:03 UTC
Labels: bug

**Comment by tlouisse** [comment] 2021-04-08 21:16
I agree it's not a bug, but didn't know where else to put it. Thanks for the tips and keep up the great work 👍
