### ISSUE TITLE
[Ziggo][OSMC] Unable to load widevine shared library

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv#66] opened 2021-09-03 12:15 UTC
This morning I got a message on OSMC (Kodi v19) to update my Widevine plugin. After following the steps in the update menu, watching TV via the Ziggo addon no longer works.

When clicking on a channel, I get the error:

> Item failed to play

The log mentions the following:

> DEBUG <general>: AddOnLog: inputstream.adaptive: CDM LoadNativeLibrary error: /home/osmc/.kodi/cdm/libwidevinecdm.so: cannot open shared object file: No such file or directory
ERROR <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/home/osmc/.kodi/cdm/libwidevinecdm.so)
ERROR <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed

I've also tried updating Widevine through SSH using the instructions on your Github, but with the same result.

**Comment by dut-iptv** [comment] 2021-09-04 10:16
Duplicate of #63

**Closed by dut-iptv** 2021-09-04 10:16 UTC
Labels: bug
