### ISSUE TITLE
T-Mobile and Ziggo both completely broken. Cannot play anything.

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#52] opened 2021-05-10 08:26 UTC
Hi! Since this morning I'm not able to play any content using the t-mobile and ziggo addons.. I tried both services using the web apps and they are working. Maybe they have changed something.. Here is a piece of the log file:

2021-05-10 10:22:52.824 T:10844   ERROR <general>: AddOnLog: inputstream.adaptive: Cannot download http://127.0.0.1:11189/tmobile/PLTV/42/224/3221236881/3221236881.mpd?rrsip=31.20.164.84:443&zoneoffset=0&devkbps=1-7000&servicetype=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&tenantId=3103&accountinfo=%7E%7EV2.0%7EsH6ldyUxa0UdX0LQmaWYXw47d039ce67a58649c3fec5a6f564776d%7E_QQf13fstz91ZUtlfuxufRQrZWeSKmjFCjW93icOs4ur0RWiR0r4aCAmgwEQKk9qf6b869b8c96949a233749bbdbf882b7b%7EExtInfoLzUGfiyVzA%2Fh6ylV0lpTyg%3D%3D7e9c470d19de83a4a375c0c1d7cda014%3A20210510082242%3AUTC%2C10001000875284%2C85.144.189.109%2C20210510082242%2C3103_TV01%2C10001000875284%2C-1%2C0%2C1%2C%2C%2C2%2C3103_BasispakketTV%2C%2C%2C2%2C10000022567533%2C0%2C10000013607052%2C0254968065%2C%2C%2C5%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAADWOywrCMBRE_ybL0NyE1i6yUgRBqmB1K7fJbSxNG02q4N9rfWxn5gxnimhos9KSbFOahZAgpSqMaVQmCVoLpckFYMkS3aqggRn0vhtdFeyMnQ7LsyiAi4LLgi-A1fPf2qPT2Wda3YeGohZ_7kDx0RnSNrX8gYmjc5EcTl0Y-d7j8xj9b8Ko_rmJHLJcKQmZUCWb5rTG1L8bdsG0DMMVI9ltcB9At-gTsSuaHh1VOJAe795_uV20b5sXnIgTHvUAAAA
2021-05-10 10:22:52.824 T:10844   ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse mpdURL (http://127.0.0.1:11189/tmobile/PLTV/42/224/3221236881/3221236881.mpd?rrsip=31.20.164.84:443&zoneoffset=0&devkbps=1-7000&servicetype=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&tenantId=3103&accountinfo=%7E%7EV2.0%7EsH6ldyUxa0UdX0LQmaWYXw47d039ce67a58649c3fec5a6f564776d%7E_QQf13fstz91ZUtlfuxufRQrZWeSKmjFCjW93icOs4ur0RWiR0r4aCAmgwEQKk9qf6b869b8c96949a233749bbdbf882b7b%7EExtInfoLzUGfiyVzA%2Fh6ylV0lpTyg%3D%3D7e9c470d19de83a4a375c0c1d7cda014%3A20210510082242%3AUTC%2C10001000875284%2C85.144.189.109%2C20210510082242%2C3103_TV01%2C10001000875284%2C-1%2C0%2C1%2C%2C%2C2%2C3103_BasispakketTV%2C%2C%2C2%2C10000022567533%2C0%2C10000013607052%2C0254968065%2C%2C%2C5%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAADWOywrCMBRE_ybL0NyE1i6yUgRBqmB1K7fJbSxNG02q4N9rfWxn5gxnimhos9KSbFOahZAgpSqMaVQmCVoLpckFYMkS3aqggRn0vhtdFeyMnQ7LsyiAi4LLgi-A1fPf2qPT2Wda3YeGohZ_7kDx0RnSNrX8gYmjc5EcTl0Y-d7j8xj9b8Ko_rmJHLJcKQmZUCWb5rTG1L8bdsG0DMMVI9ltcB9At-gTsSuaHh1VOJAe795_uV20b5sXnIgTHvUAAAA)
2021-05-10 10:22:52.824 T:10844   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Alle%20kanalen/pvr.iptvsimple_990219674.pvr]
2021-05-10 10:22:52.824 T:10844    INFO <general>: CVideoPlayer::OnExit()
2021-05-10 10:22:52.825 T:10844    INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2021-05-10 10:22:52.842 T:6396     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-05-10 10:22:52.854 T:6396     INFO <general>: CVideoPlayer::CloseFile()
2021-05-10 10:22:52.854 T:6396     INFO <general>: VideoPlayer: waiting for threads to exit
2021-05-10 10:22:52.854 T:6396     INFO <general>: VideoPlayer: finished waiting
2021-05-10 10:22:52.859 T:11496    INFO <general>: CPythonInvoker(2, C:\Users\power\AppData\Roaming\Kodi\addons\plugin.video.theoath\theoath.py): script successfully run
2021-05-10 10:22:52.926 T:9620     INFO <general>: CPythonInvoker(29, C:\Users\power\AppData\Roaming\Kodi\addons\plugin.video.tmobile\default.py): script successfully run
2021-05-10 10:22:53.057 T:11496    INFO <general>: Python interpreter stopped

EDIT: KPN is working fine.

**Comment by Pukson** [comment] 2021-05-10 13:37
T-Mobile also stopped working here, was working fine yesterday

**Comment by dut-iptv** [comment] 2021-05-12 07:56
No issues with both Ziggo and Tmobile today. I did have issues with Tmobile yesterday. Seems like a temprary issue at the provider(s)

**Comment by dut-iptv** [comment] 2021-05-14 19:00
Closing as this does not seem to be reproducable at this time and seems to be a temporary issue at the providers.

**Closed by dut-iptv** 2021-05-14 19:00 UTC
