### ISSUE TITLE
[F1 TV][1.2.9] No sound when starting a video from F1 TV

### ISSUE THREAD

**Issue by doormalena** [dut-iptv/dut-iptv#83] opened 2021-12-04 10:31 UTC
**Describe the bug**
No sound when starting a video from F1 TV.

- When there are multiple audio streams available, switching audio streams fixes the issue immediately.
- When there is just 1 audio stream available, it's not fixable.

**To Reproduce**
1. Open a video with only 1 audio stream (e.g. Tech Talk or Highlights of practices, qualification etc. Race does not matter).

**Expected behavior**
Sound is working for the default activated audio stream.

**Screenshots**
Not applicable.

**Device (please complete the following information):**
- Type: PC
- OS: Windows 10 (latest patch level)
- Browser: Not relevant
- Version: Kodi Matrix 19.3 (was also an issue with earlier versions of Kodi)

**Additional context**
I only have this issue with the F1 TV add-on. I don't use any other add-ons from this repo (no subscription). I do use other streaming add-ons such as Amazon Prime and Disney+ which do not have this issue.

Sound is passed via HDMI to Denom receiver using pass through. WASAPI or DIRECTSOUND does not make any difference. Not using pass through also does not make a difference.

Using [Race Control](https://github.com/robvdpol/RaceControl) standalone app, does not have this issue. Seems add-on and/or Kodi related.

**Comment by dut-iptv** [comment] 2021-12-04 15:06
I can confirm this issue and it does shed same light on earlier reported audio issues.

It seems to be an issue with Inputstream adaptive and the authentication cookies. These are set by the main index.m3u8 and should be used to retrieve both the audio and video m3u8 otherwise An authentication error occurs.

It looks like the video m3u8 download uses the correct authentication cookie, but this is lost when downloading the audio m3u8. If you switch audio stream the cookie is present again.

I will think about a solution. I see 2 possibilities. One is switching to DASH streams instead of HLS, but this excludes non Kodi widevine devices (iOS). The other option is trying to force the cookie by using a proxy and modifying the index.m3u8.

**Comment by dut-iptv** [comment] 2021-12-04 20:45
Ditching inputstream.adaptive and switching to inputstream.ffmpegdirect turned out to be the easiest fix.

As F1 TV Pro does not have Widevine protection at this time inputstream.adaptive is not necessary and inputstream.ffmpegdirect turns out not to exhibit the bugged behaviour of inputstream adaptive and as a bonus seems to be faster with starting the stream and seeking.

Please try 1.2.11

**Comment by doormalena** [comment] 2021-12-05 12:01
First tests are promising as-in the sound no immediately works! I will test this further.

**Comment by dut-iptv** [comment] 2021-12-06 18:55
Tested this myself on live streams and with multiple replay, shows, docu's etc. No issues found.

Marking as fixed.
Closing.

**Closed by dut-iptv** 2021-12-06 18:55 UTC
Labels: bug
