### ISSUE TITLE
[Ziggo] [1.4.4] Freezes and "Not allowed" message on other devices

### ISSUE THREAD

**Issue by Flashlab2** [dut-iptv/dut-iptv#119] opened 2022-03-07 14:31 UTC
**Describe the bug**

When I use the Ziggo Go addon in Kodi with my user credentials I can watch a stream for about 20 minutes and then it freezes; for both Live TV and Movies & Series. Restarting the stream will not work. The stream will simply not start. When I then log in on my IOS device I receive a message that tells me it can't connect to the service with the header saying "Not allowed". Strangely enough the Android TV app on my TV does work without any error messages. The situation resolves itself after a few hours. Then I can use the IOS app again and the stream will start again on the Kodi add on. But again the stream will freeze and trigger the "Not allowed" message again.

**Expected behavior**
No freezes in the stream and no trigger to the "Not allowed" status.

**Device (please complete the following information):**
- Type: Philips TV 
 - OS: Android TV 10
 - Kodi Version 19.3
 - Addon Version Latest

**Comment by eXcyle** [comment] 2022-03-10 21:06
I'm having the same issue, i did not test it with the app, but the ziggo go website gives a similar error message when logging in after "triggering" the issue. i can not confirm, but it feels like a temp ban or something.

**Comment by dut-iptv** [comment] 2022-03-11 19:58
Does this issue occur on different platforms such as a Windows/Linux laptop/desktop or Android Phone? Or only on your smart TV?

It is not something I have come accross myself, but it is very possible that Ziggo changed something in their playback routine that causes this issue.

I will try to investigate, but because of time constraints it could be a while.

**Comment by Flashlab2** [comment] 2022-03-14 14:22
For me it only happens on my TV and only on Kodi. On the same TV I have the Ziggo Go app installed too and it works fine on that.

**Comment by GithubMarcel** [comment] 2022-03-15 22:42
Same problem here on a LibreELEC install. (10.0.1)

**Comment by Clogs-n-tall** [comment] 2022-03-16 11:03
@dut-iptv Same here, Raspberry pi, Raspberry OS BullsEye, Up to date, Kodi 19.

I suspect two possible causes:
1. Multiple Logins attempts in quick succession (DDOS protect of Ziggo blocks?)
2. Incorrect UA but that does not account for the fact that it works at first.

Does the plugin have its own logging and is there a specific debug mode?

**Comment by dut-iptv** [comment] 2022-03-27 19:25
Sorry for the late response, I'm very busy at the moment.

I can confirm this issue.

Ziggo seems to have changed something in their login/session/play API which has broken the addon. I will try to work on a fix, but cannot provide an ETA.

**Comment by Flashlab2** [comment] 2022-03-31 09:44
Maybe good to reiterate is that when the "Not allowed" message appears on the iOS device the dedicated Android TV app is still able to work without any error message. Maybe this gives a clue on what happens.

Also logging in and browsing the content including refreshing the xml TV guide data on the Ziggo Go Kodi addon doesn't trigger the "Not allowed" error message. Only starting a stream does.

**Comment by dut-iptv** [comment] 2022-04-09 19:23
Sorry for the long wait. Latest version should fix the issues

Edit: 1.4.7 Hotfix released because of a breaking bug

**Comment by atreyuhere** [comment] 2022-04-10 09:03
Latest version 1.4.7 seems to have fixed the 'not allowed' issue. Thank you for looking into it.
I will keep testing some more, as it consistently showed the issue after some 20 minutes on all devices after playing something from the addon. Haven't seen the issue since the update to 1.4.7 (.6 did not start at all).
Again, thank you for fixing with limited time available !

A.

**Comment by atreyuhere** [comment] 2022-04-10 10:45
After some more testing i do encounter the 'max connections reached' again while starting another stream on the android Ziggo go app after starting a stream in the addon.  The addon stream does not get disconnected though. Not sure why the 3 stream max thing is not honoured, but at least it works 100% on 1 device at a time again

**Comment by atreyuhere** [comment] 2022-04-13 19:02
More testing done.
Unless there's other experiences I'd say this one is  fixed. Thanks!

**Comment by dut-iptv** [comment] 2022-04-15 17:57
@atreyuhere Tnx for reporting back.

Closing

**Closed by dut-iptv** 2022-04-15 17:57 UTC
Labels: bug, Confirmed
