### ISSUE TITLE
[KPN][Android/Chrome OS] Catchup only works on non-DRM channels

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#16] opened 2021-02-13 08:31 UTC
Hi!

My girlfriend is using the kpn addon with kodi 19 on her Nvidia Shield. Most things are working well, but catchup is not working on every channel. Actually, it seems that it only works on the npo channels.

rtl and others are not working. It keeps loading, but nothing happend. do you have any idea?

**Comment by dut-iptv** [comment] 2021-02-13 09:27
I have no issues with catchup on KPN on any supported (not all channels have ReplayTV and thus Catchup at KPN) channel.

Have you tested:
-That the programs you are trying to catchup are available/playable on the KPN app/website.
-That the programs you are trying to catchup are available/playable in the addon under ReplayTV.

If you can play the programs from the KPN addon please reconfigure your Simple IPTV settings through the connector and try again after.

**Comment by powermarcel10** [comment] 2021-02-13 12:11
I tried it on my chromebook and the same thing happend. Using the reply tv option in the addon, it is working fine, but using catchup in the epg, it keeps loading.

On my chromebook I did a fresh installation of the connector.

**Comment by madeby0203** [comment] 2021-02-18 10:42
With kodi 19 on my Nvidia Shield I am unable to use catchup on any channel, including NPO using the IPTV PVR. As @powermarcel10 mentioned the replay option in the addon it works fine. When watching live I am able to rewind for some minutes, but in the guide I am unable to select any show and watch it again.

**Comment by atreyuhere** [comment] 2021-03-02 13:14
@madeby0203 Have you tried clearing data for TV/Guide in Live TV settings?
I had the same issue (with Ziggo) and it was solved by clearing and reloading the tv/guide data.

**Comment by dut-iptv** [comment] 2021-03-14 10:29
I can confirm this issue exists on Google created OS'es such as Android/Android TV and Chrome OS. 

These operating systems use a different implementation of Widevine (also by Google) which seems to cause issues with the specific combination of KPN, Simple IPTV catchup, Kodi 19 and Inputstream Adaptive. 

As the implementation in all my addons and on all platforms is the same and there is no issue on regular replay TV + KPN + Android, Windows + KPN + Catchup or any of the other addons + Catchup + any platform there seems to be little I can do at this time to fix this issue.

**Comment by madeby0203** [comment] 2021-03-26 13:21
After clearing data and going through all the settings again, catchup seemed to had been disabled all together in the IPTV application. Enabling this fixed all issues and playback is extremely smooth.

**Comment by dut-iptv** [comment] 2021-12-01 18:50
@powermarcel10 

Have you recently checked if this problem still exists?

Other crashes and issues I have had in the past with PVR Simple IPTV Client have been solved in recent versions (probably mostly because of development at their end).

I don't have access to a KPN account right now to test  myself.

**Comment by dut-iptv** [comment] 2021-12-06 12:33
Was able to test this. Issue still exists and now covers all channels, meaning Catchup is not usable on KPN on Android (TV) and Chrome OS.

As this issue is not being worked on and this issue is not fixable from my end I will close this issue and add this information to the README.

**Closed by dut-iptv** 2021-12-06 12:33 UTC
Labels: bug, wontfix
