### ISSUE TITLE
[F1][1.4.5] INLOG

### ISSUE THREAD

**Issue by djdirty60** [dut-iptv/dut-iptv#129] opened 2022-06-04 22:25 UTC
Good day unfortunately can't log in with the F1 addon.

![16543814962765788583611859721996](https://user-images.githubusercontent.com/13561831/172027298-48e23163-fa1e-4c57-92ab-6b5cea7ac7d7.jpg)

**Device (please complete the following information):**
- Type: [Nvidia shield pro 2019]
 - OS: [Android]
 - Kodi Version [19.4]
 - Addon Version [1.4.5]

**Comment by dut-iptv** [comment] 2022-06-05 06:08
Duplicate of #124

**Closed as completed by dut-iptv** 2022-06-05 06:08 UTC
Labels: bug
