### ISSUE TITLE
dut-iptv 20210416 / Ziggo GO

### ISSUE THREAD

**Issue by harmjan525** [dut-iptv/dut-iptv#47] opened 2021-04-25 12:31 UTC
I installed on KODI 19.0.0 the add-on “Ziggo-GO” for watching live TV from the dutch provider Ziggo.
I used the link :  "https://github.com/dut-iptv/dut-iptv.github.io"
I installed it on “Google ChromeCast TV” .
After selecting a tv-channel, I have a good TV quality.
PROBLEM :
 Every time after a time-out of exactly 10 minutes the Ziggo channel goes back to the channel list. 
Then I have to select the channel again. And so on.
Is this a known problem and how can I repair it ???

**Comment by dvdevil** [comment] 2021-04-25 12:49
Same over here.

**Comment by dut-iptv** [comment] 2021-04-25 16:45
Please follow the issue template for your title and issue description.

Duplicate of #46 

Issue should be fixed in 1.1.7, probably related to a change in the Ziggo API or Inputstream Adaptive

**Closed by dut-iptv** 2021-04-25 16:45 UTC
Labels: bug
