### ISSUE TITLE
[NLZiet][1.3.5] Video stalls

### ISSUE THREAD

**Issue by Mislancer** [dut-iptv/dut-iptv#90] opened 2021-12-17 16:40 UTC
Hello,

For almost a week now i have this problem with a couple of channels RTL8 & NET5. We can watch the live-streams but after a while (sometimes 5 min. sometimes after 30 min.) Video stutters, then freezes and only audio is playing. Pressing x and starting the same channel will work, but I keep having the same issue. NPO channels are playing without any problems. 
I'm not sure what i can do tried reinstalling widevine, roll back python dependencies. But nothing seems to work. Do you have any idea's. 

**Device (please complete the following information):**
- Raspberry Pi 4 (Wired network)
 - Libreelec 10.0.1
 - Kodi Version 19.3
 - Addon Version e.g. 1.5.0

**Comment by dut-iptv** [comment] 2021-12-19 12:10
Have you tried if other platforms (e.g. Windows) exhibit the same behaviour?

Does the issue seem related to what is being played (e.g. does it seem to occur around the end/start of programs)?

Are any errors shown on screen?

Please also supply a debug log from Kodi in which the problem occurs

**Comment by Mislancer** [comment] 2021-12-19 14:22
I tried it o on Ubuntu using a regular web-browser, no problems with the stream. The video stall problem is not at a certain time or at the end or beginning of the program. It seems to be variable on when it's occurring.

I added the log file from the moment that I started Net5 till just after the video stalls. Hopefully it's enough for you to see what maybe is the problem. Just let me know if it's enough our i did something wrong. Thank you for your effort. 

[kodi.log](https://github.com/dut-iptv/dut-iptv/files/7740939/kodi.log)

**Comment by dut-iptv** [comment] 2021-12-19 15:11
> I tried it o on Ubuntu using a regular web-browser, no problems with the stream.

I maybe should have been more clear but I was asking if you have the same problem using Kodi and the addon on a different platform, such as Ubuntu. This would rule out LibreELEC/RPI as a factor.

Looking at your log there does seem to be an issue with my proxy for this stream (as there are 404 errors returned by the proxy). This should be reproducible by me so I can hopefully debug the issue.

**Comment by dut-iptv** [comment] 2021-12-19 16:10
When I play the Net5 livestream in a browser with a debug console on I can see the same 404 errors in the video, but the official player just silently fails on these, switches back to a slightly lower quality and switch back to the higher quality a bit later. Kodi/Inputstream Adaptive does not know how to deal with this misbehaving stream and ultimately stop playing.

So the root cause here is a bad stream from NLZiet.
This could be a temporary issue, but might also be a permanent problem. I will see if a fix/workaround is possible.

**Comment by Mislancer** [comment] 2021-12-19 16:40
Again thank you for, looking in to this. Just for me to learn, how do you run a debug in your browser. I want to check out if this is the same with RTL 8.

**Comment by dut-iptv** [comment] 2021-12-19 17:45
In this case you can just open the developer console (how depends on your browser) and open the network tab and start a stream. Look for 404 errors on .dash requests, you can usually filter the network tab so you only see requests containing .dash

**Comment by Mislancer** [comment] 2021-12-22 10:14
Not sure if you changed anything, but yesterday net5 and rtl8 seems to work again.

**Comment by dut-iptv** [comment] 2021-12-22 12:04
No I did not, so I expect/hope that NLZiet fixed their broken streams.

Will close this for now, if it pops up again regularly I will consider a workaround, but ultimately this is not an addon bug but a provider issue.

**Closed by dut-iptv** 2021-12-22 12:04 UTC
Labels: bug

**Comment by Mislancer** [comment] 2021-12-23 20:01
Thanks for your effort. Seems that NET5 still has this problem, video stalls on that channel. I'm considering email NLziet because i got some hickups while watching, using a web browser. Maybe they would look into it.

**Comment by Mislancer** [comment] 2021-12-24 16:13
Hello,

I got the following reply from NLziet on the mail I send. Seems they are working on it.

Dank voor je bericht, balen dat je hier last van hebt! 

Toevallig hebben meer mensen dit gemeld, en hebben we onze stream-leverancier aan het werk gezet om te kijken hoe dit opgelost kan worden.
