### ISSUE TITLE
[Ziggo Go][1.2.1] Widevine issue starting CE 19.2RC3

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv#60] opened 2021-08-17 07:52 UTC
**Describe the bug**
Starting Coreelec version 19.2rc3  Widevine is no longer usable with the Ziggo go addon. On Coreelec 19.2 rc2 the addon is using a slightly aged version 4.10.1610.6 which no longer works on 19.2rc3. Changing the widevine version to this older version does not solve the issue.

A possible cause could be changes in widevine versions or any binairy changes that came with it (?)

**To Reproduce**
1. Start Ziggo Go on CE 19.2 rc3
2. Start any live stream
3. An error is thrown " The System (Linux aarch64) does not yet support Widevine playback'
4. Installing Widevine from the Ziggo Go addon throws the same error

**Expected behavior**
Widevine should be operational with the latest generally used version 4.10.2252.0 

**Device (please complete the following information):**
- Type: Hardkernel C4, N2(+)
 - OS: Coreelec 19.2rc3

**Additional context**
I have created a debug log, which does not give any usable info starting channels besides these lines:
2021-08-17 09:33:44.741 T:5481    DEBUG <general>: Thread Timer start, auto delete: false
2021-08-17 09:33:44.744 T:5481    DEBUG <general>: Thread Timer 3537875584 terminating

Please let me know if you need a full debug.

**Comment by vpeter4** [comment] 2021-08-17 14:11
I think the problem is that `platform.machine()` returns `aarch64` instead of `armv7l`. It worked correctly in the past but with CoreELEC 19.2RC3 patch arch handling was changed and this bug was introduced.
And it is already fixed with https://github.com/CoreELEC/CoreELEC/commit/70f8943dd402320e1d5be6f6e8d2a7fb962cd1ee
Next CE nightly will have this included.

**Comment by atreyuhere** [comment] 2021-08-17 14:46
I want to thank you for taking the time to chime in, @vpeter. Much appreciated!

**Comment by dut-iptv** [comment] 2021-08-17 20:48
I just published 1.2.2 with the system/arch handling from util.py copied to inputstrream.py as hopefully a quick provisional fix.

When I have some time I will probably stop dealing with Widevine from the addons and switch over to inputstream helper which has recently devised a way to greatly reduce the required download/disk space when updating Widevine for arm linux (Downloading multiple gigs for a 4 MB file was the reason to not support their addon in the past)

**Comment by atreyuhere** [comment] 2021-08-18 10:56
Just to report version 1.2.2 without the commit from CE nightly did not solve it; subsewuent errors were thrown.
Updating to the latest CE nightly inclusing the fix did solve the issue.

Getting rid of the Widevine management from whitin the addon sounds very logical; i actually preferred to do it from the addon for the exact reason you mention. Did not provide the most recent version, but i figured as long as other widewine addons supported it i'd use that version. 

Thank you both for your efforts, ticket can now be closed

**Closed** 2021-08-20 13:47 UTC
Labels: bug
